////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.327.94396-live
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

using UnityEngine;

using Albion.Common.Time;

namespace Merlin.API.Direct
{
    /* Internal type: hn */
    public class HarvestableDescriptor
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        
        private hn _internal;
        
        #region Properties
        
        public hn Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public HarvestableDescriptor(hn instance)
        {
            _internal = instance;
        }
        
        static HarvestableDescriptor()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator hn(HarvestableDescriptor instance)
        {
            return instance._internal;
        }
        
        public static implicit operator HarvestableDescriptor(hn instance)
        {
            return new HarvestableDescriptor(instance);
        }
        
        #endregion
    }
}
