////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.332.98217-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Merlin.API.Direct
{
    /* Internal type: g7 */
    public partial class ActiveSpellDescriptor : SpellDescriptor
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private g7 _internal;
        
        #region Properties
        
        public g7 ActiveSpellDescriptor_Internal => _internal;
        public SpellAssessment Assesment => _internal.d5.ToWrapped();
        public SpellCategory Category => _internal.d4.ToWrapped();
        public float EnergyCost => _internal.dv;
        public SpellTarget Target => _internal.d1.ToWrapped();
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public ActiveSpellDescriptor(g7 instance) : base(instance)
        {
            _internal = instance;
        }
        
        static ActiveSpellDescriptor()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator g7(ActiveSpellDescriptor instance)
        {
            return instance._internal;
        }
        
        public static implicit operator ActiveSpellDescriptor(g7 instance)
        {
            return new ActiveSpellDescriptor(instance);
        }
        
        public static implicit operator bool(ActiveSpellDescriptor instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
