////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.327.96272-live
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Merlin.API.Direct
{
    /* Internal type: ac3 */
    public partial class BuildingDataFile : DataFile
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private ac3 _internal;
        
        #region Properties
        
        public ac3 BuildingDataFile_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public BuildingDataFile(ac3 instance) : base(instance)
        {
            _internal = instance;
        }
        
        static BuildingDataFile()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator ac3(BuildingDataFile instance)
        {
            return instance._internal;
        }
        
        public static implicit operator BuildingDataFile(ac3 instance)
        {
            return new BuildingDataFile(instance);
        }
        
        public static implicit operator bool(BuildingDataFile instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
