////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.327.97446-live
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Merlin.API.Direct
{
    /* Internal type: akh */
    public partial class ClusterExitDescriptor
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private akh _internal;
        
        #region Properties
        
        public akh ClusterExitDescriptor_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public ClusterDescriptor GetDestination() => _internal.o();
        public ClusterExitKind GetKind() => _internal.r().ToWrapped();
        public Point2 GetPosition() => _internal.v();
        public ClusterDescriptor GetSource() => _internal.l();
        public void SetDestination(ClusterDescriptor A_0) => _methodReflectionPool[0].Invoke(_internal,new object[]{(akg)A_0});
        public void SetSource(ClusterDescriptor A_0) => _methodReflectionPool[1].Invoke(_internal,new object[]{(akg)A_0});
        
        #endregion
        
        #region Constructor
        
        public ClusterExitDescriptor(akh instance)
        {
            _internal = instance;
        }
        
        static ClusterExitDescriptor()
        {
            _methodReflectionPool.Add(typeof(akh).GetMethod("l", BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance, null, new Type[]{typeof(akg)}, null));
            _methodReflectionPool.Add(typeof(akh).GetMethod("m", BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance, null, new Type[]{typeof(akg)}, null));
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator akh(ClusterExitDescriptor instance)
        {
            return instance._internal;
        }
        
        public static implicit operator ClusterExitDescriptor(akh instance)
        {
            return new ClusterExitDescriptor(instance);
        }
        
        public static implicit operator bool(ClusterExitDescriptor instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
