////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.336.100246-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Merlin.API.Direct
{
    /* Internal type: alc */
    public partial struct Duration
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        
        private alc _internal;
        
        #region Properties
        
        public alc Duration_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public Duration(alc instance)
        {
            _internal = instance;
        }
        
        static Duration()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator alc(Duration instance)
        {
            return instance._internal;
        }
        
        public static implicit operator Duration(alc instance)
        {
            return new Duration(instance);
        }
        #endregion
    }
}
