////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.327.96272-live
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Merlin.API.Direct
{
    /* Internal type: asf */
    public partial class FightingObject : MovingObject
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private asf _internal;
        
        #region Properties
        
        public asf FightingObject_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public FightingAttributes GetAttributes() => _internal.at();
        public ObservableRange<ac1> GetEnergy() => _internal.v5();
        public ObservableRange<ac1> GetHealth() => _internal.v4();
        public CharacterDescriptor GetCharacterDescriptor() => _internal.wc();
        public bool GetIsAttacking() => _internal.x0();
        public bool GetIsCasting() => _internal.xw();
        public bool GetIsDead() => _internal.jd();
        public bool GetIsChanneling() => _internal.xx();
        public bool GetIsIdle() => _internal.xv();
        public float GetLoad() => _internal.jf();
        public float GetLoadPercentage() => _internal.wf();
        public float GetLoadSpeedFactor() => _internal.wg();
        public float GetMaxLoad() => _internal.we();
        public string GetName() => _internal.ir();
        public long GetTargetId() => _internal.wa();
        public a GetEventHandler<a>() where a:asg => (a)_internal.xm<a>();
        
        #endregion
        
        #region Constructor
        
        public FightingObject(asf instance) : base(instance)
        {
            _internal = instance;
        }
        
        static FightingObject()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator asf(FightingObject instance)
        {
            return instance._internal;
        }
        
        public static implicit operator FightingObject(asf instance)
        {
            return new FightingObject(instance);
        }
        
        public static implicit operator bool(FightingObject instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
