////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.332.98217-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Merlin.API.Direct
{
    /* Internal type: a68 */
    public partial class GuiDurableItemProxy : GuiItemProxy
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private a68 _internal;
        
        #region Properties
        
        public a68 GuiDurableItemProxy_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public Number GetUnfloatyFloat() => _internal.ba();
        
        #endregion
        
        #region Constructor
        
        public GuiDurableItemProxy(a68 instance) : base(instance)
        {
            _internal = instance;
        }
        
        static GuiDurableItemProxy()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator a68(GuiDurableItemProxy instance)
        {
            return instance._internal;
        }
        
        public static implicit operator GuiDurableItemProxy(a68 instance)
        {
            return new GuiDurableItemProxy(instance);
        }
        
        public static implicit operator bool(GuiDurableItemProxy instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
