////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.327.94396-live
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Merlin.API.Direct
{
    /* Internal type: ary */
    public partial class JournalItemProxy : DurableItemProxy
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        
        private ary _internal;
        
        #region Properties
        
        public ary JournalItemProxy_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public JournalItemProxy(ary instance) : base(instance)
        {
            _internal = instance;
        }
        
        static JournalItemProxy()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator ary(JournalItemProxy instance)
        {
            return instance._internal;
        }
        
        public static implicit operator JournalItemProxy(ary instance)
        {
            return new JournalItemProxy(instance);
        }
        
        #endregion
    }
}
