////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.327.97446-live
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

using UnityEngine;

using Albion.Common.Time;

using NUnit.Framework;

namespace Merlin.API.Direct.Tests
{
    /* Internal type: akh */
    [TestFixture]
    public class ClusterExitDescriptorTests
    {
        #region Conversion
        
        [Test]
        public void SetDestination_ReflectionTest()
        {
            MethodInfo info = typeof(akh).GetMethod("l", new Type[]{typeof(akg)});
            Assert.Null(info,"Method ClusterExitDescriptor.SetDestination(akh.l) is null");
        }
        
        [Test]
        public void SetSource_ReflectionTest()
        {
            MethodInfo info = typeof(akh).GetMethod("m", new Type[]{typeof(akg)});
            Assert.Null(info,"Method ClusterExitDescriptor.SetSource(akh.m) is null");
        }
        
        
        #endregion
    }
}
