////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.336.100246-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

using UnityEngine;

using Albion.Common.Time;

using NUnit.Framework;

namespace Merlin.API.Direct.Tests
{
    /* Internal type: aed */
    [TestFixture]
    public class ObservableRangeTests
    {
        #region Conversion
        
        [Test]
        public void SetMinimum_ReflectionTest()
        {
            //MethodInfo info = typeof(aeg<aec>).GetMethod("k", new Type[]{typeof(float)});
            //Assert.Null(info,"Method ObservableRange.SetMinimum(aed.k) is null");
        }
        
        
        #endregion
    }
}
