////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.327.96272-live
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

using UnityEngine;

using Albion.Common.Time;

using NUnit.Framework;

namespace Merlin.API.Direct.Tests
{
    /* Internal type: gy */
    [TestFixture]
    public class SpellDescriptorTests
    {
        #region Conversion
        
        [Test]
        public void GetNameTag_ReflectionTest()
        {
            MethodInfo info = typeof(gy).GetMethod("h9", new Type[]{});
            Assert.Null(info,"Method SpellDescriptor.GetNameTag(gy.h9) is null");
        }
        
        
        #endregion
    }
}
