////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.10.357.113485-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: c1 */
    public partial class AgentsDataFile : DataFile
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private c1 _internal;
        
        #region Properties
        
        public c1 AgentsDataFile_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public AgentsDataFile(c1 instance) : base(instance)
        {
            _internal = instance;
        }
        
        static AgentsDataFile()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator c1(AgentsDataFile instance)
        {
            return instance._internal;
        }
        
        public static implicit operator AgentsDataFile(c1 instance)
        {
            return new AgentsDataFile(instance);
        }
        
        public static implicit operator bool(AgentsDataFile instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
