////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.336.100246-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Albion_Direct
{
    /* Internal type: agw.a */
    public enum CollisionFlags
    {
        Terrain = 0,
        Barrier = 1,
        Wall = 2,
        Unknown1 = 4,
        Unknown2 = 5,
        Building = 16,
        GameObject = 32,
        Unknown3 = 37,
        MeshCollider = 255
    }
    
    public static class CollisionFlagsExtensions
    {
        public static agw.a ToInternal(this CollisionFlags instance)
        {
            return (agw.a)instance;
        }
        
        public static CollisionFlags ToWrapped(this agw.a instance)
        {
            return (CollisionFlags)instance;
        }
    }
}
