////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.336.100246-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Reflection;

namespace Albion_Direct
{
    /* Internal type: pb */
    public partial class CompoundTileDescriptor
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private pb _internal;
        
        #region Properties
        
        public pb CompoundTileDescriptor_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public CompoundTileDescriptor(pb instance)
        {
            _internal = instance;
        }
        
        static CompoundTileDescriptor()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator pb(CompoundTileDescriptor instance)
        {
            return instance._internal;
        }
        
        public static implicit operator CompoundTileDescriptor(pb instance)
        {
            return new CompoundTileDescriptor(instance);
        }
        
        public static implicit operator bool(CompoundTileDescriptor instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
