////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.336.100246-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Reflection;

namespace Albion_Direct
{
    /* Internal type: avd */
    public partial class FarmableItemProxy : SimpleItemProxy
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private avd _internal;
        
        #region Properties
        
        public avd FarmableItemProxy_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public FarmableItemProxy(avd instance) : base(instance)
        {
            _internal = instance;
        }
        
        static FarmableItemProxy()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator avd(FarmableItemProxy instance)
        {
            return instance._internal;
        }
        
        public static implicit operator FarmableItemProxy(avd instance)
        {
            return new FarmableItemProxy(instance);
        }
        
        public static implicit operator bool(FarmableItemProxy instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
