////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.10.351.108124-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: afc */
    public partial class FightingAttributes
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private afc _internal;
        
        #region Properties
        
        public afc FightingAttributes_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public float GetEnergyRegen() => _internal.ba();
        public float GetHealthRegen() => _internal.a8();
        public float GetMaxCraftingFocus() => _internal.co();
        public float GetMaxCraftingRegeneration() => _internal.cp();
        public float GetMaxEnergy() => _internal.a9();
        public float GetMaxHealth() => _internal.a7();
        public float GetMaxLoad() => _internal.bc();
        public float GetMoveSpeed() => _internal.bb();
        
        #endregion
        
        #region Constructor
        
        public FightingAttributes(afc instance)
        {
            _internal = instance;
        }
        
        static FightingAttributes()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator afc(FightingAttributes instance)
        {
            return instance._internal;
        }
        
        public static implicit operator FightingAttributes(afc instance)
        {
            return new FightingAttributes(instance);
        }
        
        public static implicit operator bool(FightingAttributes instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
