////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.11.357.115208-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: ayf */
    public partial class FightingObject : MovingObject
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        public a GetEventHandler<a>() where a : a1e => (a)_internal.zo<a>();

        private ayf _internal;
        
        #region Properties
        
        public ayf FightingObject_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public FightingAttributes GetAttributes() => _internal.ax();
        public ObservableRange<ahs> GetEnergy() => _internal.x7();
        public ObservableRange<ahs> GetHealth() => _internal.x6();
        public CharacterDescriptor GetCharacterDescriptor() => _internal.yf();
        public bool GetIsAttacking() => _internal.z6();
        public bool GetIsCasting() => _internal.z1();
        public bool GetIsDead() => _internal.j1();
        public bool GetIsChanneling() => _internal.z2();
        public bool GetIsIdle() => _internal.z0();
        public float GetLoad() => _internal.j3();
        public float GetLoadPercentage() => _internal.yi();
        public float GetLoadSpeedFactor() => _internal.yj();
        public float GetMaxLoad() => _internal.yh();
        public string GetName() => _internal.je();
        public long GetTargetId() => _internal.yc();
        
        #endregion
        
        #region Constructor
        
        public FightingObject(ayf instance) : base(instance)
        {
            _internal = instance;
        }
        
        static FightingObject()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator ayf(FightingObject instance)
        {
            return instance._internal;
        }
        
        public static implicit operator FightingObject(ayf instance)
        {
            return new FightingObject(instance);
        }
        
        public static implicit operator bool(FightingObject instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
