////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.336.100246-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Reflection;

namespace Albion_Direct
{
    /* Internal type: at1 */
    public partial class FurnitureItemObject : DurableItemObject
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private at1 _internal;
        
        #region Properties
        
        public at1 FurnitureItemObject_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public FurnitureItemObject(at1 instance) : base(instance)
        {
            _internal = instance;
        }
        
        static FurnitureItemObject()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator at1(FurnitureItemObject instance)
        {
            return instance._internal;
        }
        
        public static implicit operator FurnitureItemObject(at1 instance)
        {
            return new FurnitureItemObject(instance);
        }
        
        public static implicit operator bool(FurnitureItemObject instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
