////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.336.100246-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Albion_Direct
{
    /* Internal type: am2 */
    public enum GameState
    {
        Unknown = 0,
        LoggingIn = 1,
        Loading = 2,
        Playing = 3
    }
    
    public static class GameStateExtensions
    {
        public static am2 ToInternal(this GameState instance)
        {
            return (am2)instance;
        }
        
        public static GameState ToWrapped(this am2 instance)
        {
            return (GameState)instance;
        }
    }
}
