////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.336.100246-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Reflection;

namespace Albion_Direct
{
    /* Internal type: a7p */
    public partial class GuiEquipmentItemProxy : GuiDurableItemProxy
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private a7p _internal;
        
        #region Properties
        
        public a7p GuiEquipmentItemProxy_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public GuiEquipmentItemProxy(a7p instance) : base(instance)
        {
            _internal = instance;
        }
        
        static GuiEquipmentItemProxy()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator a7p(GuiEquipmentItemProxy instance)
        {
            return instance._internal;
        }
        
        public static implicit operator GuiEquipmentItemProxy(a7p instance)
        {
            return new GuiEquipmentItemProxy(instance);
        }
        
        public static implicit operator bool(GuiEquipmentItemProxy instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
