////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.336.100246-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Reflection;

namespace Albion_Direct
{
    /* Internal type: a9l */
    public partial class GuiJournalItemProxy : GuiDurableItemProxy
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private a9l _internal;
        
        #region Properties
        
        public a9l GuiJournalItemProxy_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public GuiJournalItemProxy(a9l instance) : base(instance)
        {
            _internal = instance;
        }
        
        static GuiJournalItemProxy()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator a9l(GuiJournalItemProxy instance)
        {
            return instance._internal;
        }
        
        public static implicit operator GuiJournalItemProxy(a9l instance)
        {
            return new GuiJournalItemProxy(instance);
        }
        
        public static implicit operator bool(GuiJournalItemProxy instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
