////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.10.351.108124-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: a5p */
    public partial class HarvestableObject : StaticObject
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private a5p _internal;
        
        #region Properties
        
        public a5p HarvestableObject_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public ActionPoint GetActionPoint(Point2 A_0) => _internal.az((amn)A_0);
        public HarvestableDescriptor GetDescriptor() => _internal.ta();
        public HarvestableChargeDescriptor GetChargeDescriptor() => _internal.tc();
        public long GetCharges() => _internal.tl();
        public long GetMaxCharges() => _internal.tm();
        public GameTimeStamp GetProtectedUntil() => _internal.tp();
        public int GetRareState() => _internal.tk();
        public ItemDescriptor GetResourceDescriptor() => _internal.tq();
        public HarvestableTierDescriptor GetTierDescriptor() => _internal.tb();
        public EquipmentItemProxy GetTool(LocalPlayerCharacter A_0, bool A_1) => _internal.az((a0n)A_0, (bool)A_1);
        public long GetYield() => _internal.tn();
        public bool IsHarvestable() => _internal.to();
        
        #endregion
        
        #region Constructor
        
        public HarvestableObject(a5p instance) : base(instance)
        {
            _internal = instance;
        }
        
        static HarvestableObject()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator a5p(HarvestableObject instance)
        {
            return instance._internal;
        }
        
        public static implicit operator HarvestableObject(a5p instance)
        {
            return new HarvestableObject(instance);
        }
        
        public static implicit operator bool(HarvestableObject instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
