////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.11.362.117031-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: ah4 */
    public partial class ItemsDataFile : DataFile
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private ah4 _internal;
        
        #region Properties
        
        public ah4 ItemsDataFile_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public ItemsDataFile(ah4 instance) : base(instance)
        {
            _internal = instance;
        }
        
        static ItemsDataFile()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator ah4(ItemsDataFile instance)
        {
            return instance._internal;
        }
        
        public static implicit operator ItemsDataFile(ah4 instance)
        {
            return new ItemsDataFile(instance);
        }
        
        public static implicit operator bool(ItemsDataFile instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
