////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.10.351.108124-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: afe */
    public partial class LocalPlayerAttributes : FightingAttributes
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private afe _internal;
        
        #region Properties
        
        public afe LocalPlayerAttributes_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public LocalPlayerAttributes(afe instance) : base(instance)
        {
            _internal = instance;
        }
        
        static LocalPlayerAttributes()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator afe(LocalPlayerAttributes instance)
        {
            return instance._internal;
        }
        
        public static implicit operator LocalPlayerAttributes(afe instance)
        {
            return new LocalPlayerAttributes(instance);
        }
        
        public static implicit operator bool(LocalPlayerAttributes instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
