////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.11.362.118917-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: a3i */
    public partial class LocalPlayerCharacter : PlayerCharacter
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private a3i _internal;
        
        #region Properties
        
        public a3i LocalPlayerCharacter_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public ObservableRange<ah1> GetCraftingFocus() => _internal.tl();
        public Point2 GetDestination() => _internal.u2();
        public GameTimeStamp GetGlobalCooldownTimeStamp() => _internal.uy();
        public float GetSpellSlotCooldownPercent(byte A_0) => _internal.h6((byte)A_0);
        public SpellSlots GetSpellSlots() => _internal.ux();
        public float GetWeight() => _internal.vu();
        
        #endregion
        
        #region Constructor
        
        public LocalPlayerCharacter(a3i instance) : base(instance)
        {
            _internal = instance;
        }
        
        static LocalPlayerCharacter()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator a3i(LocalPlayerCharacter instance)
        {
            return instance._internal;
        }
        
        public static implicit operator LocalPlayerCharacter(a3i instance)
        {
            return new LocalPlayerCharacter(instance);
        }
        
        public static implicit operator bool(LocalPlayerCharacter instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
