////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.336.100246-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Reflection;

namespace Albion_Direct
{
    /* Internal type: afb */
    public partial class LocalPlayerAttributes : FightingAttributes
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private afb _internal;
        
        #region Properties
        
        public afb LocalPlayerAttributes_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public LocalPlayerAttributes(afb instance) : base(instance)
        {
            _internal = instance;
        }
        
        static LocalPlayerAttributes()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator afb(LocalPlayerAttributes instance)
        {
            return instance._internal;
        }
        
        public static implicit operator LocalPlayerAttributes(afb instance)
        {
            return new LocalPlayerAttributes(instance);
        }
        
        public static implicit operator bool(LocalPlayerAttributes instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
