////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.336.100246-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Reflection;

namespace Albion_Direct
{
    /* Internal type: a5l */
    public partial class LootObject : StaticObject
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private a5l _internal;
        
        #region Properties
        
        public a5l LootObject_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public LootObject(a5l instance) : base(instance)
        {
            _internal = instance;
        }
        
        static LootObject()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator a5l(LootObject instance)
        {
            return instance._internal;
        }
        
        public static implicit operator LootObject(a5l instance)
        {
            return new LootObject(instance);
        }
        
        public static implicit operator bool(LootObject instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
