////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.11.362.118917-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: f4 */
    public partial class MobCharacterDescriptor : CharacterDescriptor
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private f4 _internal;
        
        #region Properties
        
        public f4 MobCharacterDescriptor_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public MobCharacterDescriptor(f4 instance) : base(instance)
        {
            _internal = instance;
        }
        
        static MobCharacterDescriptor()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator f4(MobCharacterDescriptor instance)
        {
            return instance._internal;
        }
        
        public static implicit operator MobCharacterDescriptor(f4 instance)
        {
            return new MobCharacterDescriptor(instance);
        }
        
        public static implicit operator bool(MobCharacterDescriptor instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
