////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.336.100246-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Reflection;

namespace Albion_Direct
{
    /* Internal type: a3a */
    public partial class MountObject : StaticObject
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private a3a _internal;
        
        #region Properties
        
        public a3a MountObject_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public MountItemDescriptor GetDescriptor() => _internal.sy();
        public bool IsInRemountDistance() => _internal.s0();
        public bool IsLocalPlayers() => _internal.sz();
        
        #endregion
        
        #region Constructor
        
        public MountObject(a3a instance) : base(instance)
        {
            _internal = instance;
        }
        
        static MountObject()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator a3a(MountObject instance)
        {
            return instance._internal;
        }
        
        public static implicit operator MountObject(a3a instance)
        {
            return new MountObject(instance);
        }
        
        public static implicit operator bool(MountObject instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
