////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.10.351.108124-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: l2 */
    public partial class OperationRequestDataContract
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private l2 _internal;
        
        #region Properties
        
        public l2 OperationRequestDataContract_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public OperationRequestDataContract(l2 instance)
        {
            _internal = instance;
        }
        
        static OperationRequestDataContract()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator l2(OperationRequestDataContract instance)
        {
            return instance._internal;
        }
        
        public static implicit operator OperationRequestDataContract(l2 instance)
        {
            return new OperationRequestDataContract(instance);
        }
        
        public static implicit operator bool(OperationRequestDataContract instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
