////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.10.357.113485-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: awj */
    public partial class PhotonClient
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private awj _internal;
        
        #region Properties
        
        public awj PhotonClient_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public GameData GetGameData() => _internal.aq();
        public atm GetGamePeer() => _internal.@as();
        public atl GetChatPeer() => _internal.au();
        public static PhotonClient GetInstance() => awj.am();
        public atn GetLoginPeer() => _internal.at();
        
        #endregion
        
        #region Constructor
        
        public PhotonClient(awj instance)
        {
            _internal = instance;
        }
        
        static PhotonClient()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator awj(PhotonClient instance)
        {
            return instance._internal;
        }
        
        public static implicit operator PhotonClient(awj instance)
        {
            return new PhotonClient(instance);
        }
        
        public static implicit operator bool(PhotonClient instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
