////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.10.351.108124-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: aut */
    public partial class PhotonClient
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private aut _internal;
        
        #region Properties
        
        public aut PhotonClient_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public GameData GetGameData() => _internal.an();
        public arx GetGamePeer() => _internal.ap();
        public arw GetChatPeer() => _internal.ar();
        public static PhotonClient GetInstance() => aut.aj();
        public ary GetLoginPeer() => _internal.aq();
        
        #endregion
        
        #region Constructor
        
        public PhotonClient(aut instance)
        {
            _internal = instance;
        }
        
        static PhotonClient()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator aut(PhotonClient instance)
        {
            return instance._internal;
        }
        
        public static implicit operator PhotonClient(aut instance)
        {
            return new PhotonClient(instance);
        }
        
        public static implicit operator bool(PhotonClient instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
