////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.11.362.118917-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: a3h */
    public partial class PlayerCharacter : FightingObject
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private a3h _internal;
        
        #region Properties
        
        public a3h PlayerCharacter_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public string GetAllianceName() => _internal.kn();
        public string GetGuildName() => _internal.kh();
        public bool GetIsHarvesting() => _internal.wy();
        public bool GetIsMounted() => _internal.wo();
        public bool GetIsMounting() => _internal.w0();
        public MountItemDescriptor GetMount() => _internal.wp();
        public ObservableRange<ah4> GetMountHealth() => _internal.wq();
        public PlayerCharacterDescriptor GetPlayerDescriptor() => _internal.wj();
        public ObservableRange<ah2> GetReputation() => _internal.wr();
        public Guid GetUid() => _internal.aw();
        
        #endregion
        
        #region Constructor
        
        public PlayerCharacter(a3h instance) : base(instance)
        {
            _internal = instance;
        }
        
        static PlayerCharacter()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator a3h(PlayerCharacter instance)
        {
            return instance._internal;
        }
        
        public static implicit operator PlayerCharacter(a3h instance)
        {
            return new PlayerCharacter(instance);
        }
        
        public static implicit operator bool(PlayerCharacter instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
