////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.336.100246-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Reflection;


namespace Albion_Direct
{
    /* Internal type: ayq */
    public partial class PlayerCharacter : FightingObject
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private ayq _internal;
        
        #region Properties
        
        public ayq PlayerCharacter_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public string GetAllianceName() => _internal.jr();
        public string GetGuildName() => _internal.jl();
        public bool GetIsHarvesting() => _internal.v8();
        public bool GetIsMounted() => _internal.vx();
        public bool GetIsMounting() => _internal.v9();
        public MountItemDescriptor GetMount() => _internal.vy();
        public ObservableRange<aec> GetMountHealth() => _internal.vz();
        public PlayerCharacterDescriptor GetPlayerDescriptor() => _internal.vs();
        public ObservableRange<aea> GetReputation() => _internal.v0();
        public Guid GetUid() => _internal.@as();
        
        #endregion
        
        #region Constructor
        
        public PlayerCharacter(ayq instance) : base(instance)
        {
            _internal = instance;
        }
        
        static PlayerCharacter()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator ayq(PlayerCharacter instance)
        {
            return instance._internal;
        }
        
        public static implicit operator PlayerCharacter(ayq instance)
        {
            return new PlayerCharacter(instance);
        }
        
        public static implicit operator bool(PlayerCharacter instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
