////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.336.100246-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Reflection;

namespace Albion_Direct
{
    /* Internal type: aff */
    public partial class PlayerCharacterDescriptor : CharacterDescriptor
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private aff _internal;
        
        #region Properties
        
        public aff PlayerCharacterDescriptor_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public float GetHarvestRange() => _internal.dw();
        public int GetInventorySize() => _internal.dv();
        public float GetUseObjectRange() => _internal.dx();
        
        #endregion
        
        #region Constructor
        
        public PlayerCharacterDescriptor(aff instance) : base(instance)
        {
            _internal = instance;
        }
        
        static PlayerCharacterDescriptor()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator aff(PlayerCharacterDescriptor instance)
        {
            return instance._internal;
        }
        
        public static implicit operator PlayerCharacterDescriptor(aff instance)
        {
            return new PlayerCharacterDescriptor(instance);
        }
        
        public static implicit operator bool(PlayerCharacterDescriptor instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
