////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.10.357.113485-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: a2f */
    public partial class PlayerCharacter : FightingObject
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private a2f _internal;
        
        #region Properties
        
        public a2f PlayerCharacter_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public string GetAllianceName() => _internal.kb();
        public string GetGuildName() => _internal.j5();
        public bool GetIsHarvesting() => _internal.ww();
        public bool GetIsMounted() => _internal.wm();
        public bool GetIsMounting() => _internal.wy();
        public MountItemDescriptor GetMount() => _internal.wn();
        public ObservableRange<ahc> GetMountHealth() => _internal.wo();
        public PlayerCharacterDescriptor GetPlayerDescriptor() => _internal.wh();
        public ObservableRange<aha> GetReputation() => _internal.wp();
        public Guid GetUid() => _internal.aw();
        
        #endregion
        
        #region Constructor
        
        public PlayerCharacter(a2f instance) : base(instance)
        {
            _internal = instance;
        }
        
        static PlayerCharacter()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator a2f(PlayerCharacter instance)
        {
            return instance._internal;
        }
        
        public static implicit operator PlayerCharacter(a2f instance)
        {
            return new PlayerCharacter(instance);
        }
        
        public static implicit operator bool(PlayerCharacter instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
