////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.10.357.113485-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Albion_Direct
{
    /* Internal type: jz.PvpRules */
    public enum PvpRules
    {
        PvpDisabled = 0,
        PvpAllowed = 1,
        PvpForced = 2
    }
    
    public static class PvpRulesExtensions
    {
        public static jz.PvpRules ToInternal(this PvpRules instance)
        {
            return (jz.PvpRules)instance;
        }
        
        public static PvpRules ToWrapped(this jz.PvpRules instance)
        {
            return (PvpRules)instance;
        }
    }
}
