////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.336.100246-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Reflection;

namespace Albion_Direct
{
    /* Internal type: a0z */
    public partial class RemotePlayerCharacter : PlayerCharacter
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private a0z _internal;
        
        #region Properties
        
        public a0z RemotePlayerCharacter_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public RemotePlayerCharacter(a0z instance) : base(instance)
        {
            _internal = instance;
        }
        
        static RemotePlayerCharacter()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator a0z(RemotePlayerCharacter instance)
        {
            return instance._internal;
        }
        
        public static implicit operator RemotePlayerCharacter(a0z instance)
        {
            return new RemotePlayerCharacter(instance);
        }
        
        public static implicit operator bool(RemotePlayerCharacter instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
