////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.11.357.114130-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: axa */
    public partial class SimulationObject
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private axa _internal;
        
        #region Properties
        
        public axa SimulationObject_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public long GetId() => _internal.a0();
        
        #endregion
        
        #region Constructor
        
        public SimulationObject(axa instance)
        {
            _internal = instance;
        }
        
        static SimulationObject()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator axa(SimulationObject instance)
        {
            return instance._internal;
        }
        
        public static implicit operator SimulationObject(axa instance)
        {
            return new SimulationObject(instance);
        }
        
        public static implicit operator bool(SimulationObject instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
