////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.0.336.100246-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Reflection;

namespace Albion_Direct
{
    /* Internal type: avv */
    public partial class SpellEffectAreaObject : MovingObject
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private avv _internal;
        
        #region Properties
        
        public avv SpellEffectAreaObject_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public ActiveSpellDescriptor GetDescriptor() => _internal.s8();
        
        #endregion
        
        #region Constructor
        
        public SpellEffectAreaObject(avv instance) : base(instance)
        {
            _internal = instance;
        }
        
        static SpellEffectAreaObject()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator avv(SpellEffectAreaObject instance)
        {
            return instance._internal;
        }
        
        public static implicit operator SpellEffectAreaObject(avv instance)
        {
            return new SpellEffectAreaObject(instance);
        }
        
        public static implicit operator bool(SpellEffectAreaObject instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
