////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.11.362.118917-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Albion_Direct
{
    /* Internal type: cx.SpellAssessment */
    public enum SpellAssessment
    {
        Negative = 0,
        Positive = 1
    }
    
    public static class SpellAssessmentExtensions
    {
        public static cx.SpellAssessment ToInternal(this SpellAssessment instance)
        {
            return (cx.SpellAssessment)instance;
        }
        
        public static SpellAssessment ToWrapped(this cx.SpellAssessment instance)
        {
            return (SpellAssessment)instance;
        }
    }
}
