////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.10.357.113485-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: ah5 */
    public partial class SpellSlot
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private ah5 _internal;
        
        #region Properties
        
        public ah5 SpellSlot_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public float GetCooldownPercent(GameTimeStamp A_0) => _internal.n((GameTimeStamp)A_0);
        public GameTimeStamp GetCooldownTimeStamp() => _internal.o();
        public CastSpellDescriptor GetSpellDescriptor() => _internal.k();
        
        #endregion
        
        #region Constructor
        
        public SpellSlot(ah5 instance)
        {
            _internal = instance;
        }
        
        static SpellSlot()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator ah5(SpellSlot instance)
        {
            return instance._internal;
        }
        
        public static implicit operator SpellSlot(ah5 instance)
        {
            return new SpellSlot(instance);
        }
        
        public static implicit operator bool(SpellSlot instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
