////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.11.357.114734-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: a8g */
    public partial class TerritoryObject : StaticObject
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private a8g _internal;
        
        #region Properties
        
        public a8g TerritoryObject_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        public TerritoryDescriptor GetDescriptor() => _internal.ts();
        
        #endregion
        
        #region Constructor
        
        public TerritoryObject(a8g instance) : base(instance)
        {
            _internal = instance;
        }
        
        static TerritoryObject()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator a8g(TerritoryObject instance)
        {
            return instance._internal;
        }
        
        public static implicit operator TerritoryObject(a8g instance)
        {
            return new TerritoryObject(instance);
        }
        
        public static implicit operator bool(TerritoryObject instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
