////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.10.357.113485-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: aih */
    public partial class TileDescriptor
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private aih _internal;
        
        #region Properties
        
        public aih TileDescriptor_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public TileDescriptor(aih instance)
        {
            _internal = instance;
        }
        
        static TileDescriptor()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator aih(TileDescriptor instance)
        {
            return instance._internal;
        }
        
        public static implicit operator TileDescriptor(aih instance)
        {
            return new TileDescriptor(instance);
        }
        
        public static implicit operator bool(TileDescriptor instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
