////////////////////////////////////////////////////////////////////////////////////
// Merlin API for Albion Online v1.11.362.118917-prod
////////////////////////////////////////////////////////////////////////////////////
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;

using UnityEngine;

using Albion.Common.Time;

namespace Albion_Direct
{
    /* Internal type: rt */
    public partial class TimeRegionDescriptor
    {
        private static List<MethodInfo> _methodReflectionPool = new List<MethodInfo>();
        private static List<PropertyInfo> _propertyReflectionPool = new List<PropertyInfo>();
        private static List<FieldInfo> _fieldReflectionPool = new List<FieldInfo>();
        
        private rt _internal;
        
        #region Properties
        
        public rt TimeRegionDescriptor_Internal => _internal;
        
        #endregion
        
        #region Fields
        
        
        #endregion
        
        #region Methods
        
        
        #endregion
        
        #region Constructor
        
        public TimeRegionDescriptor(rt instance)
        {
            _internal = instance;
        }
        
        static TimeRegionDescriptor()
        {
            
        }
        
        #endregion
        
        #region Conversion
        
        public static implicit operator rt(TimeRegionDescriptor instance)
        {
            return instance._internal;
        }
        
        public static implicit operator TimeRegionDescriptor(rt instance)
        {
            return new TimeRegionDescriptor(instance);
        }
        
        public static implicit operator bool(TimeRegionDescriptor instance)
        {
            return instance._internal != null;
        }
        #endregion
    }
}
